### ISSUE TITLE
Fix responsiveness of Members page

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#113]
Make the page responsive for tablets/ipads/kindles or medium screen size devices

<img src="https://github.com/user-attachments/assets/da2a7377-0d18-47ba-9ecc-cb06d0c9cfad" alt="Description" width="400"/>

**Comment by igAbhinav007** [comment]
Assign this to me.

**Comment by igAbhinav007** [comment]
Please checkout https://github.com/singh-ab/APS_IIITDMJ/pull/115 this pull request.
