### ISSUE TITLE
Removing Session link

### ISSUE THREAD

**Issue by igABHINAV** [singh-ab/APS_IIITDMJ#28]
remove the Session link from the navbar

**Comment by Cyberhunk49** [comment]
Hi @igABHINAV ,

I’m  Devansh, and I’m interested in contributing to APS_IIITDMJ. I’m relatively new to open-source contributions, but I’m eager to start and learn from working on meaningful issues. Could you please help me get started by assigning me this "good first issue"?

**Comment by Cyberhunk49** [comment]
![Screenshot 2024-10-27 005654](https://github.com/user-attachments/assets/58be9dbb-ce21-41fd-8434-b1ceecd13352)
is it alright? I have also removed it from another pages where its not working.

**Comment by singh-ab** [comment]
> Hi @igABHINAV ,
> 
> I’m Devansh, and I’m interested in contributing to APS_IIITDMJ. I’m relatively new to open-source contributions, but I’m eager to start and learn from working on meaningful issues. Could you please help me get started by assigning me this "good first issue"?

Assigned the issue to you
