### ISSUE TITLE
Create Outreach page

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#41]

**Comment by singh-ab** [comment]
A page needs to be created where we can showcase club outreach as well as allow other persons/institutions to reach out to the club

**Comment by Palash3101** [comment]
Hi @singh-ab, 
I'd like to work on the issue...
I will, remake the "forms" page to the outreach page, and redirect the footer link there...

**Comment by singh-ab** [comment]
Hi @Palash3101 , I'll assign this issue to you. If you want to make changes to the footer however, you'll need to get the issue #65 assigned to you.

**Comment by Palash3101** [comment]
What kind of content would you want on the page...
I think on adding the Coordinator, Co-cordinator and the official contacts of the org.
What else could I add...
