### ISSUE TITLE
Create Gallery page

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#43]

**Comment by DevanshXerc90** [comment]
hi @singh-ab , can you assign this task to me?

**Comment by singh-ab** [comment]
> hi @singh-ab , can you assign this task to me?

Sure, I've assigned it to you.

**Comment by singh-ab** [comment]
Also bear in mind the styling and responsiveness of the page

**Comment by DevanshXerc90** [comment]
sure, will try to work on it.
