### ISSUE TITLE
Change page title

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#54]
Change page title from "aps-iiitdmj.vercel.app" to "Astronomy and Physics Society" or "APS"
Also remove the vercel logo. If possible, add the APS logo.

**Comment by AMAN081118** [comment]
Hi @singh-ab,

I’m Aman, and I’m interested in contributing to APS_IIITDMJ. I’m relatively new to open-source contributions, but I’m eager to start and learn from working on meaningful issues. Could you please help me get started by assigning me this "good first issue"?

**Comment by singh-ab** [comment]
Hi, I've assigned the issue to you.
