### ISSUE TITLE
Redirection to form page missing

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#59]
Redirection to form page missing in the hero section of the landing page. Need to add redirection to the "Form" page

**Comment by AMAN081118** [comment]
Hi @singh-ab, can you assign me this issue?

**Comment by Harshvardhan1012** [comment]
HI  @singh-ab  can i know exactly what is the issue as redirection is working properly

**Comment by singh-ab** [comment]
Y

> HI @singh-ab can i know exactly what is the issue as redirection is working properly

Hi @Harshvardhan1012 . It's a very basic issue with missing URL to help people who are just getting started in development.

**Comment by BlackEyes09** [comment]
I recently fixed it. assign me and close the issue.

**Comment by singh-ab** [comment]
It doesn't work in the deployed version. I'm assigning it to you, fix this in the next PR.

**Comment by BlackEyes09** [comment]
Check the new pr
