### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by singh-ab** [singh-ab/APS_IIITDMJ#70]
- Check for errors in grammar, syntax of example codes in README, code of conduct and contributing
- Remove Hacktoberfest image from README.md

**Comment by singh-ab** [comment]
Suggest any other changes in documentation here

**Comment by AMAN081118** [comment]
Hi @singh-ab,  
Could you please assign this issue to me?

**Comment by singh-ab** [comment]
assigned to you @AMAN081118
